# Numpy

In [2]:
#To use real world mathematics
a=[2,3]
a*2

[2, 3, 2, 3]

In [3]:
import numpy 

In [4]:
import numpy as np

In [5]:
!pip install numpy

In [6]:
a_n=np.array(a)


In [7]:
a_n

array([2, 3])

In [8]:
a_n*2

array([4, 6])

# Example 1:

In [9]:
marks=[56,66,76,45,66,77,56,76,98,44]
marks=np.array(marks)
np.mean(marks)

66.0

In [10]:
np.amin(marks)

44

In [11]:
np.amax(marks)

98

In [12]:
np.median(marks)

66.0

In [13]:
np.ptp(marks)

54

In [14]:
np.std(marks)

15.716233645501712

In [15]:
np.var(marks)

247.0

In [16]:
x=[34,45,67,78]
x_n=np.array(x)
np.std(x)

17.392527130926087

In [17]:
#variance
ss=np.mean((x_n-np.mean(x_n))**2)
ss

302.5

In [18]:
from numpy import random


In [19]:
random.rand()

0.16771094539828735

In [20]:
for i in range(10):
    print(random.rand())

0.35573345175176085
0.4802803096334257
0.5077848572986674
0.9019600343289295
0.42422115388352877
0.7736245424917075
0.7770431141000117
0.4453869321643339
0.35462050349793495
0.7171669216372664


In [21]:
x=2.75


In [22]:
x=1+(1-3.5)*x
x

-5.875

In [23]:
x=2.75
for i in range(10):
    x=1+(1-3.5)*x
    print(x)
    

-5.875
15.6875
-38.21875
96.546875
-240.3671875
601.91796875
-1503.794921875
3760.4873046875
-9400.21826171875
23501.545654296875


In [24]:
# seed method is used for value initializing in random
random.seed(12)
for i in range(10):
    print(random.rand())

0.15416284237967237
0.7400496965154048
0.26331501518513467
0.5337393933802977
0.014574962485419674
0.918747008099885
0.9007148541170122
0.03342142762634459
0.9569493362751168
0.13720932135607644


In [26]:
a=[3,4] , [5,6]

In [27]:
a

([3, 4], [5, 6])

In [28]:
a[0][0]

3

In [29]:
a[0][1]

4

In [30]:
a[1][0]

5

In [31]:
a[1][1]

6

In [32]:
import numpy as np 
a_n=np.array(a)
a_n

array([[3, 4],
       [5, 6]])

In [33]:
a_n[0,:]

array([3, 4])

In [36]:
a_n[1,:]

array([5, 6])

In [38]:
a_n.dtype

dtype('int32')

In [39]:
a_n.strides

(8, 4)

In [40]:
a_n+1

array([[4, 5],
       [6, 7]])

In [41]:
a_n.shape

(2, 2)

In [42]:
b_n=np.array([1])


In [43]:
b_n

array([1])

In [44]:
b_n.shape

(1,)

# Case Study

In [47]:
#How to take data form github
import numpy as np
a=np.loadtxt("https://raw.githubusercontent.com/goradbj/MachineLearning/main/cric.tsv", skiprows=1)

In [48]:
a

array([[  0., 100.,  78., 342.],
       [  1.,  11.,  62., 191.],
       [  2.,   8.,  85., 252.],
       [  3.,  71.,  24., 307.],
       [  4., 104.,  17., 229.],
       [  5.,  18., 104., 246.],
       [  6.,   8.,  76., 226.],
       [  7.,  86.,  74., 288.],
       [  8.,  12.,  60., 216.],
       [  9.,  25.,  90., 304.],
       [ 10.,  56.,   6., 272.],
       [ 11.,  88.,  69., 302.],
       [ 12., 147.,  65., 312.],
       [ 13., 121., 146., 370.],
       [ 15.,  99., 110., 362.]])

In [49]:
sachin_runs=a[:,1]

In [50]:
sachin_runs

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  25.,  56.,
        88., 147., 121.,  99.])

In [51]:
np.mean(sachin_runs)

63.6

In [52]:
dravid_runs=a[:,2]

In [53]:
dravid_runs

array([ 78.,  62.,  85.,  24.,  17., 104.,  76.,  74.,  60.,  90.,   6.,
        69.,  65., 146., 110.])

In [54]:
np.mean(dravid_runs)

71.06666666666666

In [55]:
teamindia_runs=a[:,3]

In [56]:
teamindia_runs

array([342., 191., 252., 307., 229., 246., 226., 288., 216., 304., 272.,
       302., 312., 370., 362.])

In [57]:
np.mean(teamindia_runs)

281.26666666666665

In [58]:
np.corrcoef(sachin_runs,teamindia_runs)

array([[1.        , 0.70460106],
       [0.70460106, 1.        ]])

In [59]:
np.corrcoef(dravid_runs,teamindia_runs)

array([[1.        , 0.44853003],
       [0.44853003, 1.        ]])

In [60]:
np.corrcoef(sachin_runs,dravid_runs)

array([[1.        , 0.04899219],
       [0.04899219, 1.        ]])